[package]
name = "direnv"
desc = "Unclutter your .profile — an environment switcher for your shell"
homepage = "https://github.com/direnv/direnv"
license = "MIT"

[[version]]
ver = "2.37.1"

[[version.asset]]
os = "macos"
arch = "arm64"
url = "https://github.com/direnv/direnv/releases/download/v2.37.1/direnv.darwin-arm64"
sha256 = "4f569f3a36732bfd8b8fea7bfcc6ad87a59745c109022164d0ca4832451d5369"

[install]
strategy = "lua"
script = "install.lua"

[[provides]]
bin = ["direnv"]

[livecheck]
strategy = "github-release"
repo = "direnv/direnv"
regex = 'v(\d+\.\d+\.\d+)'
