[package]
name = "fzf"
desc = "A command-line fuzzy finder"
homepage = "https://github.com/junegunn/fzf"
license = "MIT"

[[version]]
ver = "0.74.2"

[[version.asset]]
os = "macos"
arch = "arm64"
url = "https://github.com/junegunn/fzf/releases/download/v0.74.2/fzf-0.74.2-darwin_arm64.tar.gz"
sha256 = "d60ddb36356566ac69bae7c3504e888916cf747c9ad2132141c09229b1e28dee"

[install]
strategy = "steps"

[[install.step]]
extract = "${asset}"

[[install.step]]
copy = { from = "fzf", to = "${prefix}/bin/fzf" }

[[provides]]
bin = ["fzf"]

[livecheck]
strategy = "github-release"
repo = "junegunn/fzf"
regex = 'v?(\d+\.\d+\.\d+)'
