[package]
name = "bat"
desc = "A cat clone with syntax highlighting and Git integration"
homepage = "https://github.com/sharkdp/bat"
license = "MIT OR Apache-2.0"

[[version]]
ver = "0.26.1"

[[version.asset]]
os = "macos"
arch = "arm64"
url = "https://github.com/sharkdp/bat/releases/download/v0.26.1/bat-v0.26.1-aarch64-apple-darwin.tar.gz"
sha256 = "e30beff26779c9bf60bb541e1d79046250cb74378f2757f8eb250afddb19e114"

[install]
strategy = "steps"

[[install.step]]
extract = "${asset}"

[[install.step]]
copy = { from = "bat-v0.26.1-aarch64-apple-darwin/bat", to = "${prefix}/bin/bat" }

[[provides]]
bin = ["bat"]

[livecheck]
strategy = "github-release"
repo = "sharkdp/bat"
regex = 'v?(\d+\.\d+\.\d+)'
