[package]
name = "delta"
desc = "A syntax-highlighting pager for git, diff, and grep output"
homepage = "https://github.com/dandavison/delta"
license = "MIT"

[[version]]
ver = "0.19.2"

[[version.asset]]
os = "macos"
arch = "arm64"
url = "https://github.com/dandavison/delta/releases/download/0.19.2/delta-0.19.2-aarch64-apple-darwin.tar.gz"
sha256 = "9be36612a5a13e9e386dc498fb8e50dc87c72ee42b63db0ea05b32f99a72a69a"

[install]
strategy = "steps"

[[install.step]]
extract = "${asset}"

[[install.step]]
copy = { from = "delta-0.19.2-aarch64-apple-darwin/delta", to = "${prefix}/bin/delta" }

[[provides]]
bin = ["delta"]

[livecheck]
strategy = "github-release"
repo = "dandavison/delta"
regex = '(\d+\.\d+\.\d+)'
